# =========================================================================
# REACT (VITE) STATIC APP — devShell + Nix-built nginx image
# =========================================================================
# Generated by:  nix flake init -t ~/.omni-nix#react
#
# Defines:
#   1. devShells.default — nodejs + npm + wrangler, direnv-loaded.
#   2. packages.image    — an OCI image: nginx serving the built static app.
#   3. packages.site     — the built static app itself (Cloudflare Pages upload).
#
# ⚠️ DEPS HASH (inherent to reproducible JS builds in Nix): buildNpmPackage
# needs `npmDepsHash` matching app/package-lock.json. This template SHIPS the
# real hash (it matches the committed app/package-lock.json), so `just build`
# works out of the box. When you change deps:
#   1. enter the shell:       direnv allow   (or `nix develop`)
#   2. refresh the lockfile:  (cd app && npm install)
#   3. just relock            # recomputes the hash + writes it into npmDepsHash below
#   4. just build
# (Re-run `just relock` whenever deps change — it runs prefetch-npm-deps for you.)
#
# Dev → deploy loop (after the hash is set):
#     just build && just push && just deploy        # k3s (local)
#     just cf                                        # Cloudflare Pages (public)
# =========================================================================
{
  description = "React (Vite) app — Nix devShell + nginx image, just → k3s";

  inputs.nixpkgs.url = "nixpkgs/nixos-26.05";

  outputs = { self, nixpkgs }:
    let
      systems = [ "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
      pkgsFor = system: nixpkgs.legacyPackages.${system};

      imageName = "localhost:5000/restor8-frontend";   # keep in lockstep with justfile + manifests
      imageTag  = "latest";
    in {
      packages = forAllSystems (system:
        let
          pkgs = pkgsFor system;
          lib  = nixpkgs.lib;

          # ── build the static app (reproducible, OFFLINE via npmDepsHash) ──
          # buildNpmPackage runs `npm ci` (offline, deps resolved from the
          # hash) then `npm run build` → dist/. installPhase exposes dist/.
          reactBuild = pkgs.buildNpmPackage {
            pname = "restor8-frontend";
            version = "0.1.0";
            src = ./app;
            npmDepsHash = "sha256-YrZXjj6gUqbRhC3eZr0/QuH7ePurXZHRekU4xBLrerQ=";  # from app/package-lock.json via just relock
            dontNpmBuild = false;            # run `npm run build` (the default)
            installPhase = ''
              runHook preInstall
              mkdir -p $out
              cp -r dist/* $out/
              runHook postInstall
            '';
          };

          # ── nginx config (same writable-path + docroot pattern as #hugo) ──
          nginxConf = pkgs.writeText "nginx.conf" ''
            daemon off;              # foreground (PID 1) — daemon mode forks + the container exits
            worker_processes 1;
            error_log /dev/stderr warn;
            pid        /tmp/nginx.pid;
            events { worker_connections 1024; }
            http {
              access_log /dev/stdout;
              client_body_temp_path /tmp/client_temp;
              proxy_temp_path       /tmp/proxy_temp;
              fastcgi_temp_path     /tmp/fastcgi_temp;
              uwsgi_temp_path       /tmp/uwsgi_temp;
              scgi_temp_path        /tmp/scgi_temp;
              include ${pkgs.nginx}/conf/mime.types;
              default_type application/octet-stream;
              server {
                listen 8080;          # non-root can't bind <1024; 8080 is the safe high port
                root  ${reactBuild};
                index index.html;
                # SPA fallback: serve index.html for client-side routes.
                location / { try_files $uri $uri/ /index.html; }
              }
            }
          '';

          # Non-root user (UID 1000) baked in so the manifest can set
          # runAsNonRoot + runAsUser=1000. nginx runs as this uid.
          nonRootUser = pkgs.runCommand "non-root-user" { } ''
            mkdir -p $out/etc
            printf 'root:x:0:0::/root:/bin/sh\nappuser:x:1000:1000::/nonexistent:/bin/sh\n' > $out/etc/passwd
            printf 'root:x:0:\nappuser:x:1000:\n'                                       > $out/etc/group
          '';
        in {
          default = self.packages.${system}.image;
          site  = reactBuild;          # built static app → `nix build .#site` (Cloudflare Pages upload)
          image = pkgs.dockerTools.buildImage {
            name = imageName;
            tag  = imageTag;
            copyToRoot = [
              pkgs.nginx
              reactBuild
              nonRootUser
            ];
            config = {
              User         = "1000:1000";
              # -e /dev/stderr: pre-config error log to stderr (never /var/log/nginx).
              # /tmp (pid+temp) comes from mounts: emptyDir in k3s, --tmpfs in `just test`.
              Cmd          = [ "${pkgs.nginx}/bin/nginx" "-c" nginxConf "-e" "/dev/stderr" ];
              ExposedPorts = { "8080/tcp" = { }; };
            };
          };
        });

      devShells = forAllSystems (system:
        let pkgs = pkgsFor system; in {
          default = pkgs.mkShell {
            packages = with pkgs; [
              nodejs_22    # includes npm — dev + image both use npm (no pnpm drift)
              just skopeo kubectl
              wrangler     # Cloudflare Pages direct-upload deploy (just cf)
            ];
            shellHook = ''
              echo ""
              echo "  ❯ react devshell active"
              echo "      node    $(node -v 2>/dev/null || echo '—')"
              echo "      image   ${imageName}:${imageTag}"
              echo "      serve   npm run dev   (→ http://localhost:5173)"
              echo "      deploy  just build && just push && just deploy   (k3s)"
              echo "      cf      just cf                                          (Cloudflare Pages)"
              echo "      deps    (cd app && npm install) → just relock → just build"
              echo ""
            '';
          };
        });
    };
}
